custombucket = "pgpproject"
table = "intellipaat"
databasehost = "intellipaat-pgp.cixixytyimq2.us-west-2.rds.amazonaws.com"
duser = "intel"
dpass = "intel123"
s3database = "intellipaat"
kapp = "http://192.168.2.200:32219"
